New UI ✨
hashicorp/swingset pull request #131
Opened 2023-07-19 20:31 UTC by prestonbourne

[Preview](https://swingset-example-git-presnavdesign-hashicorp.vercel.app/swingset)

# Summary
This PR does the following

- Adds a navigation bar at the top per design spec
- Changes `Chevron` into `Bottom` icon per design spec

2023-07-19 20:34 UTC, prestonbourne commented on packages/swingset-theme-hashicorp/src/components/app-wrapper.tsx
> +            'ss-flex ss-flex-col ss-flex-grow ss-m-auto ss-max-w-5xl ss-mb-24 ss-transition-all',
`ss-mb-24` Ensures the last piece of content doesnt get clipped as part of the overflow.
Creating the margin pushes the `div` up

2023-07-19 21:40 UTC, dstaley requested changes
This is looking great!! Just one comment about readability.

2023-07-19 21:40 UTC, dstaley commented on packages/swingset-theme-hashicorp/src/components/app-wrapper.tsx
> +            isOpen && 'ss-w-1/2'
I think this would be more readable as a ternary expression.

```
isOpen ? `ss-w-1/2' : 'ss-w-2/3'
```

2023-07-19 21:40 UTC, dstaley commented on packages/swingset-theme-hashicorp/src/components/side-nav/toggle-button.tsx
> +        !isOpen && 'ss--rotate-90',
Same comment as above!

2023-07-21 17:15 UTC, dstaley approved these changes

2023-07-24 19:12 UTC, merged